name: bpgbouncer
version: 0.2.0
description: Chart for PGBouncer
keywords:
- postgresql
- database
- sql
home: https://pgbouncer.github.io
sources:
- https://github.com/clearbit/charts
maintainers:
- name: bbenlazreg
  email: ops@futuretech.industries
engine: gotpl
